// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOxEh33PCLhpUfHOqvN0J2g_N0QaMsvo',
    appId: '1:294786905270:web:be9e3fe17afd0925fca217',
    messagingSenderId: '294786905270',
    projectId: 'food-29bd5',
    authDomain: 'food-29bd5.firebaseapp.com',
    storageBucket: 'food-29bd5.firebasestorage.app',
    measurementId: 'G-TVC6J1CL6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1fFoyNn1tijfDyyikXhXtle_oRCJZ0g',
    appId: '1:294786905270:android:19bb806d9180a8a2fca217',
    messagingSenderId: '294786905270',
    projectId: 'food-29bd5',
    storageBucket: 'food-29bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLfP2qRBITI_jxlE3G6rJnJ3kIn_Pb4g',
    appId: '1:294786905270:ios:0a06c3087a9028bafca217',
    messagingSenderId: '294786905270',
    projectId: 'food-29bd5',
    storageBucket: 'food-29bd5.firebasestorage.app',
    iosBundleId: 'com.example.foodtemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLfP2qRBITI_jxlE3G6rJnJ3kIn_Pb4g',
    appId: '1:294786905270:ios:0a06c3087a9028bafca217',
    messagingSenderId: '294786905270',
    projectId: 'food-29bd5',
    storageBucket: 'food-29bd5.firebasestorage.app',
    iosBundleId: 'com.example.foodtemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpOxEh33PCLhpUfHOqvN0J2g_N0QaMsvo',
    appId: '1:294786905270:web:40de9dd3baf7f2f9fca217',
    messagingSenderId: '294786905270',
    projectId: 'food-29bd5',
    authDomain: 'food-29bd5.firebaseapp.com',
    storageBucket: 'food-29bd5.firebasestorage.app',
    measurementId: 'G-2EF70EWKHQ',
  );
}
